apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaspy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaspy
  template:
    metadata:
      labels:
        app: schemaspy
    spec:
      initContainers:
      - name: schemaspy
        image: schemaspy/schemaspy:latest
        args:
          - "-t"
          - "pgsql"
          - "-host"
          - "postgres.default.svc.cluster.local"
          - "-port"
          - "5432"
          - "-db"
          - "platform_development"
          - "-u"
          - "postgres"
          - "-p"
          - "development"
          - "-s"
          - "public"
        volumeMounts:
        - name: output-volume
          mountPath: /output
      containers:
      - name: webserver
        image: nginx:alpine
        volumeMounts:
        - name: output-volume
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: output-volume
        emptyDir: {}
